# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Supabase.CLI
PackageVersion: 2.119.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: supabase.exe
  PortableCommandAlias: supabase
ArchiveBinariesDependOnPath: true
Commands:
- supabase
ReleaseDate: 2026-09-30
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/supabase/cli/releases/download/v2.119.0/supabase_2.119.0_windows_amd64.zip
  InstallerSha256: DB4A6EC26D182408CA605EFC0D0D938720BD2D8D39541E79C7D69043897AFFB9
- Architecture: arm64
  InstallerUrl: https://github.com/supabase/cli/releases/download/v2.119.0/supabase_2.119.0_windows_arm64.zip
  InstallerSha256: DEDAA94379FBB49695F2A30DB351759A947813455D061492818BCCEAD4534947
ManifestType: installer
ManifestVersion: 1.12.0
