# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: coolLabs.CoolifyCLI
PackageVersion: 1.8.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: coolify.exe
  PortableCommandAlias: coolify
Commands:
- coolify
ReleaseDate: 2026-08-19
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/coollabsio/coolify-cli/releases/download/v1.8.0/coolify-cli_1.8.0_windows_amd64.zip
  InstallerSha256: DB4B770E60F4FC8BDC9B5855661FC00CB19FD325B77DB75AE0DD43D68B3F8285
- Architecture: arm64
  InstallerUrl: https://github.com/coollabsio/coolify-cli/releases/download/v1.8.0/coolify-cli_1.8.0_windows_arm64.zip
  InstallerSha256: 5FE1CB8B88712119E7AEB72C6E6DA62C1B55CD275ED4828D9815191CDE371E98
ManifestType: installer
ManifestVersion: 1.12.0
